const Store={
  key:'sageAI_v3',
  default:{page:'home',explored:[],discovered:[],observationDone:false,observationTime:0,prediction:null,confidence:null,predictionReason:'',lab:{heat:'Medium',amount:'Medium',air:'Medium',temp:'Normal'},experimentA:null,evidence:false,cycleSeq:[],cycle:false,reasonText:'',environment:false,envChoice:'',envReason:'',reflection:{r1:'',r2:'',r3:''},achievements:[]},
  load(){try{return {...this.default,...JSON.parse(localStorage.getItem(this.key)||'{}')}}catch{return {...this.default}}},
  save(){localStorage.setItem(this.key,JSON.stringify(App.state))}
};
const REQUIRED_OBJECTS=['sun','cloud','mountain','plant','lake','river','soil'];
const STEPS=['world','explore','predict','lab','evidence','challenge','environment','reflect'];
const UI={
  modal(html){document.getElementById('modalContent').innerHTML=html;document.getElementById('modal').classList.remove('hidden')},
  closeModal(){document.getElementById('modal').classList.add('hidden')},
  toast(t){const x=document.createElement('div');x.className='toast';x.textContent=t;document.body.appendChild(x);setTimeout(()=>x.remove(),1800)}
};
const App={
  state:Store.load(),
  init(){this.render()},
  isComplete(page){const s=this.state;return ({world:REQUIRED_OBJECTS.every(k=>s.explored.includes(k)),explore:s.observationDone,predict:!!(s.prediction&&s.predictionReason&&s.confidence),lab:!!s.experimentA,evidence:s.evidence,challenge:s.cycle&&!!s.reasonText,environment:s.environment,reflect:Object.values(s.reflection||{}).every(v=>String(v).trim().length>=5)})[page]||false},
  canAccess(page){if(page==='home'||page==='profile')return page==='profile'?this.isComplete('reflect'):true;const i=STEPS.indexOf(page);if(i<0)return false;return i===0||this.isComplete(STEPS[i-1])},
  nextPage(page){const i=STEPS.indexOf(page);return i<0?null:STEPS[i+1]||'profile'},
  go(page){if(!this.canAccess(page)){UI.toast('Selesaikan tahap sebelumnya dulu ya.');return}this.state.page=page;Store.save();this.render()},
  reset(){if(confirm('Mulai kembali dari awal? Semua progress akan dihapus.')){localStorage.removeItem(Store.key);this.state=Store.load();this.render();}},
  progress(){return Math.round((STEPS.filter(p=>this.isComplete(p)).length/STEPS.length)*100)},
  unlock(id){if(!this.state.achievements.includes(id)){this.state.achievements.push(id);Store.save();UI.toast('Pencapaian baru terbuka!')}},
  render(){const p=this.state.page||'home';const views={home:this.home,world:this.world,explore:this.explore,predict:this.predict,lab:this.lab,evidence:this.evidence,challenge:this.challenge,environment:this.environment,reflect:this.reflect,profile:this.profile};document.getElementById('screen').innerHTML=views[p].call(this);this.afterRender()},
  afterRender(){
    const pr=this.progress();document.getElementById('progressBar').style.width=pr+'%';document.getElementById('progressLabel').textContent=pr+'% perjalanan';
    document.querySelectorAll('[data-nav]').forEach(b=>{const target=b.dataset.nav;const locked=!this.canAccess(target);b.classList.toggle('active',target===this.state.page);b.classList.toggle('locked',locked);b.disabled=locked;b.title=locked?'Selesaikan tahap sebelumnya dulu':'';});
    if(!document.getElementById('sageBox'))document.body.insertAdjacentHTML('beforeend',`<div id="sageBox" class="sage"><div class="sage-head"><div class="sage-avatar">🌿</div><div><strong>SAGE</strong><small>Pendamping Investigasi</small></div><button class="sage-close" onclick="SAGE.close()">×</button></div><p id="sageText"></p></div>`);
    document.querySelectorAll('.draggable').forEach(el=>this.enableDrag(el));
    const obs=document.getElementById('obsTime');if(obs)this.observeTime(obs.value);
  },
  home(){const p=this.progress();return `<div class="page home-page"><section class="home-main"><div class="eyebrow">SMART ADAPTIVE GUIDE</div><div class="home-title"><div class="leaf">🌿</div><div><h1>SAGE-AI</h1><p>Laboratorium Sains Digital</p></div></div><h2>Selidiki ke mana perginya air.</h2><p class="lead">Amati → Prediksi → Eksperimen → Buktikan</p><div class="mission-line"><span>💧</span><b>Misi:</b> gunakan bukti untuk menjelaskan perjalanan air.</div><button class="btn btn-primary big-btn" onclick="App.go('world')">${this.isComplete('world')?'Lanjut Investigasi →':'Mulai Investigasi →'}</button></section><section class="home-side"><div class="journey-title"><b>Jalur Investigasi</b><span>${p}%</span></div><div class="journey-map">${[['01','Explore','world'],['02','Observe','explore'],['03','Predict','predict'],['04','Experiment','lab'],['05','Analyze','evidence'],['06','Explain','challenge'],['07','Connect','environment'],['08','Reflect','reflect']].map((x,i)=>`<div class="journey-step ${this.isComplete(x[2])?'done':''} ${!this.canAccess(x[2])?'locked':''}"><strong>${x[0]}</strong><span>${x[1]}</span>${this.isComplete(x[2])?'<em>✓</em>':''}</div>`).join('')}</div><div class="home-bottom"><div class="bar"><i style="width:${p}%"></i></div><small>${p===100?'Perjalanan selesai!':'Tahap berikutnya akan terbuka setelah tahap sebelumnya selesai.'}</small></div></section></div>`},
  world(){const found=this.state.explored.filter(x=>REQUIRED_OBJECTS.includes(x)).length;return `<div class="page world-page"><div class="page-head"><div><div class="eyebrow">01 · EXPLORE</div><h2>Dunia Air</h2><p>Sentuh atau geser objek untuk menemukan petunjuk.</p></div><div class="counter">${found}/${REQUIRED_OBJECTS.length}</div></div><div class="world" id="worldScene"><div class="world-hint">Gerakkan objek untuk menyelidiki</div><button class="obj draggable sun" data-key="sun" style="left:78%;top:7%">☀️<span>Matahari</span></button><button class="obj draggable cloud" data-key="cloud" style="left:27%;top:12%">☁️<span>Awan</span></button><button class="obj draggable mountain" data-key="mountain" style="left:6%;top:48%">🏔️<span>Pegunungan</span></button><button class="obj draggable plant" data-key="plant" style="left:35%;top:69%">🌳<span>Tumbuhan</span></button><button class="obj draggable lake" data-key="lake" style="left:7%;top:78%">💧<span>Danau</span></button><button class="obj draggable river" data-key="river" style="left:78%;top:76%">🏞️<span>Sungai</span></button><button class="obj draggable soil" data-key="soil" style="left:53%;top:78%">🌱<span>Tanah</span></button><button class="obj draggable ocean" data-key="ocean" style="left:45%;top:47%">🌊<span>Laut</span></button><div class="rain-drop">💧</div></div><div class="world-bottom"><div class="discoveries">${['Evaporasi','Transpirasi','Kondensasi','Presipitasi','Infiltrasi','Runoff'].map(x=>`<span class="tag ${this.state.discovered.includes(x)?'found':'locked'}">${this.state.discovered.includes(x)?'✓':'○'} ${x}</span>`).join('')}</div><button class="btn btn-primary" onclick="App.go('explore')" ${found<REQUIRED_OBJECTS.length?'disabled':''}>Lanjut Pengamatan →</button></div></div>`},
  enableDrag(el){let down=false,moved=false,sx=0,sy=0,sl=0,st=0;el.addEventListener('pointerdown',e=>{down=true;moved=false;sx=e.clientX;sy=e.clientY;sl=parseFloat(el.style.left);st=parseFloat(el.style.top);el.setPointerCapture?.(e.pointerId);el.classList.add('dragging')});el.addEventListener('pointermove',e=>{if(!down)return;const dx=(e.clientX-sx)/el.parentElement.clientWidth*100,dy=(e.clientY-sy)/el.parentElement.clientHeight*100;if(Math.abs(dx)+Math.abs(dy)>2)moved=true;el.style.left=Math.max(1,Math.min(92,sl+dx))+'%';el.style.top=Math.max(3,Math.min(88,st+dy))+'%'});el.addEventListener('pointerup',e=>{if(!down)return;down=false;el.classList.remove('dragging');if(!moved)this.inspect(el.dataset.key)})},
  inspect(key){const o=DATA.objects[key];if(!o)return;if(!this.state.explored.includes(key))this.state.explored.push(key);const process={sun:'Evaporasi',ocean:'Evaporasi',cloud:'Kondensasi',plant:'Transpirasi',river:'Runoff',soil:'Infiltrasi',mountain:'Runoff',lake:'Evaporasi'}[key];if(process&&!this.state.discovered.includes(process))this.state.discovered.push(process);this.unlock('explore');Store.save();UI.modal(`<div class="eyebrow">PETUNJUK DITEMUKAN</div><div class="modal-icon">${o.icon}</div><h2>${o.name}</h2><p>${o.info}</p><div class="notice"><b>Coba pikirkan:</b><br>${o.q}</div><div class="modal-actions"><button class="btn btn-soft" onclick="UI.closeModal();SAGE.show('${o.q.replace(/'/g,"\\'")}')">Tanya SAGE</button><button class="btn btn-primary" onclick="UI.closeModal();App.render()">Lanjut ✓</button></div>`)},
  explore(){const t=this.state.observationTime||0;return `<div class="page activity-page"><div class="page-head"><div><div class="eyebrow">02 · OBSERVE</div><h2>Amati Sebelum Menebak</h2><p>Geser waktu dan lihat perubahan genangan.</p></div><span class="status-dot">● Observasi</span></div><div class="observe-card"><div class="observe-scene"><div class="obs-sun">☀️</div><div class="obs-cloud">☁️</div><div class="obs-ground"></div><div class="puddle" id="puddle"><span>💧</span></div><div class="obs-vapor" id="obsVapor">· · ·</div></div><div class="time-row"><b>Waktu</b><input id="obsTime" type="range" min="0" max="3" value="${t}" oninput="App.observeTime(this.value)"><span id="obsLabel">Awal</span></div><div class="observe-note" id="obsNote">Genangan masih terlihat jelas.</div></div><div class="action-row"><button class="btn btn-soft" onclick="SAGE.show('Perhatikan ukuran genangan. Apa yang berubah ketika waktu berlalu?')">Petunjuk SAGE</button><button class="btn btn-primary" onclick="App.finishObserve()" ${t<1?'disabled':''}>Selesai Mengamati →</button></div></div>`},
  observeTime(v){const sizes=[72,58,42,25],labels=['Awal','Beberapa menit','Lebih lama','Setelah cukup lama'],notes=['Genangan masih terlihat jelas.','Permukaan air mulai berkurang.','Genangan tampak semakin kecil.','Sebagian air tidak lagi terlihat di permukaan.'];const p=document.getElementById('puddle'),lab=document.getElementById('obsLabel'),note=document.getElementById('obsNote'),vap=document.getElementById('obsVapor');if(p)p.style.width=sizes[Number(v)]+'%';if(lab)lab.textContent=labels[Number(v)];if(note)note.textContent=notes[Number(v)];if(vap)vap.style.opacity=Number(v)>0?1:0;this.state.observationTime=Number(v);Store.save()},
  finishObserve(){if(this.state.observationTime<1){UI.toast('Geser waktu dulu untuk melihat perubahan.');return}this.state.observationDone=true;Store.save();this.go('predict')},
  predict(){const answers=['Air menghilang begitu saja','Air berubah menjadi uap','Air berubah menjadi tanah','Belum yakin'];return `<div class="page activity-page"><div class="page-head"><div><div class="eyebrow">03 · PREDICT</div><h2>Buat Prediksimu</h2><p>Prediksi boleh salah. Yang penting ada alasan.</p></div><span class="status-dot">● Dugaan</span></div><div class="predict-card"><div class="question"><span>Pertanyaan</span><h3>Ke mana perginya air dari genangan?</h3><div class="answer-grid">${answers.map(a=>`<button class="answer ${this.state.prediction===a?'selected':''}" onclick="App.selectPrediction('${a}')">${a}</button>`).join('')}</div></div><div class="predict-side"><label>Alasanmu <small>1–2 kalimat cukup.</small></label><textarea id="predReason" class="input compact" placeholder="Karena..." oninput="App.state.predictionReason=this.value;Store.save()">${this.state.predictionReason||''}</textarea><div class="confidence"><b>Seberapa yakin?</b>${['Belum yakin','Cukup yakin','Sangat yakin'].map(c=>`<button class="${this.state.confidence===c?'active':''}" onclick="App.selectConfidence('${c}')">${c}</button>`).join('')}</div><div class="edit-note">Kamu masih bisa mengubah prediksi selama tahap ini.</div></div></div><div class="action-row"><button class="btn btn-soft" onclick="SAGE.show('Prediksi boleh berubah setelah ada bukti. Jangan takut mencoba.')">Petunjuk SAGE</button><button class="btn btn-primary" onclick="App.savePrediction()">Simpan & Eksperimen →</button></div></div>`},
  selectPrediction(a){this.state.prediction=a;Store.save();this.render();SAGE.show(SAGE.prediction(a,this.state.confidence))},
  selectConfidence(c){this.state.confidence=c;Store.save();this.render()},
  savePrediction(){const r=document.getElementById('predReason').value.trim();this.state.predictionReason=r;if(!this.state.prediction||!r||!this.state.confidence){Store.save();UI.toast('Lengkapi prediksi, alasan, dan tingkat keyakinan dulu.');return}this.unlock('predict');Store.save();this.go('lab')},
  lab(){const vals=[['heat','☀️ Panas',['Low','Medium','High']],['amount','💧 Jumlah air',['Low','Medium','High']],['air','💨 Angin',['Low','Medium','High']],['temp','🌡️ Suhu',['Cool','Normal','Warm']]];return `<div class="page lab-page"><div class="page-head"><div><div class="eyebrow">04 · EXPERIMENT</div><h2>Laboratorium Penguapan</h2><p>Ubah kondisi lalu lihat perubahan datanya.</p></div><span class="status-dot">● Eksperimen</span></div><div class="lab-grid"><div class="control-panel">${vals.map(c=>`<div class="control"><label>${c[1]}<span>${this.state.lab[c[0]]}</span></label><select id="${c[0]}">${c[2].map(v=>`<option ${this.state.lab[c[0]]===v?'selected':''}>${v}</option>`).join('')}</select></div>`).join('')}<button class="btn btn-primary" onclick="App.runExperiment()">▶ Jalankan Simulasi</button></div><div class="experiment"><div class="beaker"><div class="steam" id="steam">💨</div><div class="beaker-glass"><div class="water" id="water"></div></div></div><div class="experiment-state">${this.state.experimentA?'Hasil terakhir tersimpan.':'Siap diuji.'}</div><div id="results">${this.state.experimentA?this.resultHTML(this.state.experimentA):'<div class="empty">Atur variabel lalu jalankan.</div>'}</div></div></div><div class="action-row"><button class="btn btn-soft" onclick="SAGE.show('Untuk melihat pengaruh suatu faktor, coba ubah satu variabel saja.')">Tips SAGE</button><button class="btn btn-primary" onclick="App.go('evidence')" ${this.state.experimentA?'':'disabled'}>Analisis Data →</button></div></div>`},
  resultHTML(r){return `<div class="data-grid"><div class="metric"><small>Laju</small><strong>${r.rate}%</strong></div><div class="metric"><small>Uap air</small><strong>${r.vapor}</strong></div><div class="metric"><small>Waktu</small><strong>${r.time} mnt</strong></div></div><div class="bar"><i style="width:${r.rate}%"></i></div>`},
  runExperiment(){const s={heat:document.getElementById('heat').value,amount:document.getElementById('amount').value,air:document.getElementById('air').value,temp:document.getElementById('temp').value};this.state.lab=s;const r=Simulation.run(s);this.state.experimentA={...r,settings:s};this.unlock('experiment');Store.save();this.render();setTimeout(()=>{document.getElementById('steam')?.classList.add('show');const w=document.getElementById('water');if(w)w.style.height=r.remaining+'%';SAGE.show(SAGE.result(r))},120)},
  evidence(){const r=this.state.experimentA;return `<div class="page activity-page"><div class="page-head"><div><div class="eyebrow">05 · ANALYZE</div><h2>Temukan Buktinya</h2><p>Gunakan hasil eksperimenmu, bukan tebakan.</p></div><span class="status-dot">● Data</span></div><div class="data-review"><div class="card data-card"><div class="card-title"><b>Data percobaan</b><span>${r?`${r.settings.heat} panas · ${r.settings.air} angin · ${r.settings.temp}`:'Belum ada'}</span></div>${r?this.resultHTML(r):'<div class="empty">Kembali ke laboratorium untuk menjalankan simulasi.</div>'}</div><div class="card"><h3>Mana yang paling membantu menjelaskan penguapan?</h3><div class="answer-grid">${['Laju penguapan','Waktu percobaan','Semua data di atas'].map((x,i)=>`<button class="answer ${this.state.evidence&&i===2?'correct':''}" onclick="App.markEvidence(${i})">${x}</button>`).join('')}</div><div class="notice small-notice">Gunakan lebih dari satu data agar kesimpulanmu lebih kuat.</div></div></div><div class="action-row"><button class="btn btn-soft" onclick="SAGE.show('Bandingkan laju, uap air, dan waktu. Apa yang kamu lihat dari ketiganya?')">Bantuan SAGE</button><button class="btn btn-primary" onclick="App.go('challenge')" ${this.state.evidence?'':'disabled'}>Lanjut Explain →</button></div></div>`},
  markEvidence(i){if(i===2){this.state.evidence=true;this.unlock('evidence');Store.save();this.render();SAGE.show('Bagus. Kamu memakai seluruh data sebelum membuat kesimpulan.')}else SAGE.show('Coba lihat ketiga data sekaligus. Kesimpulan tidak hanya bergantung pada satu angka.')},
  challenge(){const seq=this.state.cycleSeq||[];const steps=['Evaporasi','Kondensasi','Presipitasi','Infiltrasi'];return `<div class="page activity-page"><div class="page-head"><div><div class="eyebrow">06 · EXPLAIN</div><h2>Susun Siklus Air</h2><p>Pilih proses satu per satu. Bisa diulang kalau salah.</p></div><span class="counter">${seq.length}/4</span></div><div class="cycle-board"><div class="cycle-slots">${steps.map((_,i)=>`<button class="cycle-slot ${seq[i]?'filled':''}" onclick="App.removeCycle(${i})">${seq[i]||'?'}${seq[i]?'<small>× hapus</small>':''}</button>${i<3?'<span>→</span>':''}`).join('')}</div><div class="processes">${steps.map(x=>`<button class="process ${seq.includes(x)?'used':''}" ${seq.includes(x)?'disabled':''} onclick="App.chooseCycle('${x}')">${x}</button>`).join('')}</div><div class="cycle-status">${this.state.cycle?'✓ Urutan tepat.':'Susun dari proses yang terjadi setelah air menerima panas.'}</div><button class="retry-link" onclick="App.resetCycle()">↻ Ulangi susunan</button></div><div class="reason-card"><label><b>Jelaskan temuanmu</b><small>Hubungkan dengan hasil eksperimen.</small></label><textarea id="reason" class="input compact" placeholder="Panas membuat air..." oninput="App.state.reasonText=this.value;Store.save()">${this.state.reasonText||''}</textarea></div><div class="action-row"><button class="btn btn-soft" onclick="SAGE.show('Setelah air menguap, uap air mendingin dan dapat mengalami kondensasi.')">Petunjuk SAGE</button><button class="btn btn-primary" onclick="App.saveReason()" ${this.state.cycle?'':'disabled'}>Simpan Penjelasan →</button></div></div>`},
  chooseCycle(x){const seq=this.state.cycleSeq||[];if(seq.includes(x))return;seq.push(x);this.state.cycleSeq=seq;if(seq.length===4){this.state.cycle=seq.join('|')==='Evaporasi|Kondensasi|Presipitasi|Infiltrasi';if(!this.state.cycle)SAGE.show('Urutannya belum tepat. Kamu bisa menekan Ulangi Susunan lalu mencoba lagi.')}Store.save();this.render()},
  removeCycle(i){const seq=this.state.cycleSeq||[];if(i===seq.length-1){seq.pop();this.state.cycle=false;Store.save();this.render()}else UI.toast('Hapus dari urutan paling belakang dulu.')},
  resetCycle(){this.state.cycleSeq=[];this.state.cycle=false;Store.save();this.render()},
  saveReason(){const t=document.getElementById('reason').value.trim();this.state.reasonText=t;if(t.length<10){Store.save();UI.toast('Jelaskan sedikit lebih lengkap.');return}if(!this.state.cycle){UI.toast('Perbaiki urutan siklus dulu.');return}this.unlock('reason');Store.save();this.go('environment')},
  environment(){const options=['Tanaman dapat kekurangan air','Air tanah dan permukaan dapat berubah','Kondisi lingkungan dapat terpengaruh','Semua kemungkinan perlu dipertimbangkan'];return `<div class="page activity-page"><div class="page-head"><div><div class="eyebrow">07 · CONNECT</div><h2>Sains di Lingkungan</h2><p>Hubungkan siklus air dengan keadaan sekitar.</p></div><span class="status-dot">● Lingkungan</span></div><div class="environment-card"><div class="env-scene"><span>☁️</span><span>🌧️</span><span>🌱</span></div><div class="env-question"><h3>Hujan sangat sedikit selama beberapa minggu.</h3><p>Apa yang mungkin terjadi pada lingkungan?</p><div class="answer-grid">${options.map(x=>`<button class="answer ${this.state.envChoice===x?'selected':''}" onclick="App.envAnswer('${x}')">${x}</button>`).join('')}</div></div><div class="env-reason"><label>Alasanmu <small>Jelaskan hubungan sebab-akibat.</small></label><textarea id="envText" class="input compact" placeholder="Karena..." oninput="App.state.envReason=this.value;Store.save()">${this.state.envReason||''}</textarea></div></div><div class="action-row"><button class="btn btn-soft" onclick="SAGE.show('Pikirkan hubungan hujan, tanah, tumbuhan, dan ketersediaan air.')">Petunjuk SAGE</button><button class="btn btn-primary" onclick="App.saveEnv()" ${this.state.envChoice?'':'disabled'}>Lanjut Refleksi →</button></div></div>`},
  envAnswer(x){this.state.envChoice=x;Store.save();this.render()},
  saveEnv(){const t=document.getElementById('envText').value.trim();this.state.envReason=t;if(t.length<10){Store.save();UI.toast('Tambahkan alasan singkat.');return}this.state.environment=true;this.unlock('environment');Store.save();this.go('reflect')},
  reflect(){const r=this.state.reflection||{};return `<div class="page activity-page"><div class="page-head"><div><div class="eyebrow">08 · REFLECT</div><h2>Refleksi Ilmuwan</h2><p>Catat apa yang kamu pelajari dari penyelidikan.</p></div><span class="counter">3 pertanyaan</span></div><div class="reflection-grid">${[['r1','Apa hal baru yang kamu temukan?'],['r2','Apakah hasil eksperimen sesuai prediksi?'],['r3','Apa yang akan kamu ubah jika mengulang?']].map((x,i)=>`<div class="card reflection-card"><span>${i+1}</span><label>${x[1]}</label><textarea id="${x[0]}" class="input compact" placeholder="Tulis jawabanmu..." oninput="App.state.reflection['${x[0]}']=this.value;Store.save()">${r[x[0]]||''}</textarea></div>`).join('')}</div><div class="action-row"><button class="btn btn-soft" onclick="SAGE.show('Refleksi membantu ilmuwan melihat apa yang berhasil dan apa yang bisa diperbaiki.')">Petunjuk SAGE</button><button class="btn btn-primary" onclick="App.saveReflection()">Selesaikan Perjalanan →</button></div></div>`},
  saveReflection(){const r={r1:document.getElementById('r1').value.trim(),r2:document.getElementById('r2').value.trim(),r3:document.getElementById('r3').value.trim()};if(Object.values(r).some(x=>x.length<5)){UI.toast('Lengkapi ketiga refleksi dulu.');return}this.state.reflection=r;this.unlock('sage');Store.save();this.go('profile')},
  profile(){const s=this.state,p=this.progress();return `<div class="page profile-page"><section class="profile-head"><div><div class="eyebrow">YOUR SCIENTIST PROFILE</div><h1>Profil Ilmuwan</h1><p>Jejak belajar berdasarkan aktivitas yang kamu selesaikan.</p></div><div class="profile-pct"><strong>${p}%</strong><span>selesai</span></div></section><div class="profile-stats"><div><b>${s.explored.filter(x=>REQUIRED_OBJECTS.includes(x)).length}</b><small>Objek</small></div><div><b>${s.experimentA?1:0}</b><small>Eksperimen</small></div><div><b>${s.discovered.length}</b><small>Temuan</small></div><div><b>${s.achievements.length}/8</b><small>Badge</small></div></div><section class="achievement-strip">${DATA.achievements.map(a=>`<div class="achievement ${s.achievements.includes(a[0])?'':'locked'}"><div>${a[1]}</div><b>${a[2]}</b><small>${s.achievements.includes(a[0])?'Terbuka':'Terkunci'}</small></div>`).join('')}</section><div class="completion-card">🎉 ${p===100?'Perjalanan investigasi selesai!':'Masih ada tahap yang belum selesai.'}<button class="btn btn-primary" onclick="App.go('home')">Kembali ke Beranda</button></div></div>`}
};
document.addEventListener('DOMContentLoaded',()=>App.init());
