const Store={
  key:"sageAI_v1",
  default:{page:"home",discovered:[],explored:[],prediction:null,confidence:null,predictionReason:"",experimentA:null,experimentB:null,evidence:false,reason:false,cycle:false,environment:false,reflection:{},achievements:[]},
  load(){try{return {...this.default,...JSON.parse(localStorage.getItem(this.key)||"{}")}}catch{return {...this.default}}},
  save(){localStorage.setItem(this.key,JSON.stringify(App.state))}
};
const UI={
  modal(html){document.getElementById("modalContent").innerHTML=html;document.getElementById("modal").classList.remove("hidden")},
  closeModal(){document.getElementById("modal").classList.add("hidden")},
  toast(t){const x=document.createElement("div");x.className="toast";x.textContent=t;document.body.appendChild(x);setTimeout(()=>x.remove(),2200)}
};
const App={
  state:Store.load(),
  pages:["home","world","explore","predict","lab","evidence","challenge","environment","reflect","profile"],
  init(){this.render();},
  go(page){this.state.page=page;Store.save();this.render();window.scrollTo({top:0,behavior:"smooth"})},
  reset(){if(confirm("Mulai kembali dari awal? Progress akan dihapus.")){localStorage.removeItem(Store.key);this.state=Store.load();this.render();}},
  progress(){
    const s=this.state;
    const checks=[s.explored.length>0,s.discovered.length>=1,!!s.prediction,!!s.experimentA,!!s.evidence,!!s.reason,!!s.cycle,!!s.environment,Object.keys(s.reflection).length>=3];
    return Math.round(checks.filter(Boolean).length/checks.length*100);
  },
  unlock(id){
    if(!this.state.achievements.includes(id)){this.state.achievements.push(id);Store.save();UI.toast("🏆 Pencapaian baru terbuka!");}
  },
  render(){
    const p=this.state.page||"home";
    const views={home:this.home,world:this.world,explore:this.explore,predict:this.predict,lab:this.lab,evidence:this.evidence,challenge:this.challenge,environment:this.environment,reflect:this.reflect,profile:this.profile};
    document.getElementById("screen").innerHTML=`<div class="screen">${views[p].call(this)}</div>`;
    this.afterRender();
  },
  afterRender(){
    const pr=this.progress();
    document.getElementById("progressBar").style.width=pr+"%";
    document.getElementById("progressLabel").textContent=pr+"% perjalanan";
    document.querySelectorAll("[data-nav]").forEach(b=>b.classList.toggle("active",b.dataset.nav===this.state.page));
    const sage=`<div id="sageBox" class="sage"><div class="sage-head"><div class="sage-avatar">🌿</div><div><strong>SAGE</strong><small>Science Mentor</small></div><button class="sage-close" onclick="SAGE.close()">×</button></div><p id="sageText"></p></div>`;
    document.body.insertAdjacentHTML("beforeend",sage);
  },
  home(){return `
    <section class="hero"><div class="eyebrow">Smart Adaptive Guide for Environmental Learning</div><h1>SAGE-AI 🌿</h1><h2>Laboratorium Sains Digital</h2><p><b>“Jangan hanya belajar bagaimana siklus air bekerja. Selidiki mengapa itu terjadi.”</b></p><p>Halo, Ilmuwan Muda! 🔬 Hari ini kamu akan menyelidiki ke mana perginya air dan menggunakan bukti untuk menjelaskan temuannya.</p><button class="btn btn-primary" onclick="App.go('world')">Mulai Investigasi →</button></section>
    <section class="section"><div class="mission"><div class="big">💧</div><div><h3>Misi: Ke Mana Perginya Air?</h3><p>Amati lingkungan, buat prediksi, jalankan eksperimen, lalu buktikan dengan data.</p></div></div></section>
    <section class="section"><div class="section-title"><h2>Perjalanan Ilmuwan</h2><p>Explore → Observe → Predict → Experiment → Analyze → Explain → Reflect</p></div><div class="cards">
      ${[["🔎","Eksplorasi","Temukan bagian-bagian Dunia Air."],["🔮","Prediksi","Nyatakan dugaanmu sebelum eksperimen."],["🔬","Eksperimen","Ubah variabel dan lihat akibatnya."],["📊","Bukti","Gunakan data eksperimenmu."],["🧠","Penalaran","Jelaskan apa yang kamu temukan."],["🌱","Aksi","Hubungkan sains dengan lingkungan."]].map((x,i)=>`<div class="card"><div class="mini-icon">${x[0]}</div><h3>${x[1]}</h3><p>${x[2]}</p></div>`).join("")}</div></section>
    <section class="section"><div class="section-title"><h2>Progress</h2><p>${this.progress()}% selesai</p></div><div class="cards">${["Observasi","Prediksi","Eksperimen","Bukti","Penalaran","Refleksi"].map((x,i)=>`<div class="card"><h3>${x}</h3><div class="bar"><i style="width:${[this.state.explored.length?100:0,this.state.prediction?100:0,this.state.experimentA?100:0,this.state.evidence?100:0,this.state.reason?100:0,Object.keys(this.state.reflection).length>=3?100:0][i]}%"></i></div></div>`).join("")}</div></section>`},
  world(){const o=DATA.objects;return `<div class="section-title"><div><div class="eyebrow">01 · Explore</div><h2>Dunia Air 🌎</h2><p>Sentuh objek untuk menyelidiki perannya.</p></div></div>
    <div class="world">
      <button class="obj sun" onclick="App.inspect('sun')">☀️<span>Matahari</span></button>
      <button class="obj cloud" onclick="App.inspect('cloud')">☁️<span>Awan</span></button>
      <button class="obj cloud2" onclick="App.inspect('cloud')">☁️</button>
      <button class="obj mountain" onclick="App.inspect('mountain')">🏔️<span>Pegunungan</span></button>
      <button class="obj tree" onclick="App.inspect('plant')">🌳<span>Tumbuhan</span></button>
      <button class="obj tree2" onclick="App.inspect('plant')">🌲</button>
      <button class="obj lake" onclick="App.inspect('lake')">💧<span>Danau</span></button>
      <button class="obj river" onclick="App.inspect('river')">🏞️<span>Sungai</span></button>
      <button class="obj soil" onclick="App.inspect('soil')">🌱<span>Tanah</span></button>
      <button class="obj rain" onclick="App.inspect('cloud')">🌧️<span>Hujan</span></button>
      <div class="ocean-label">🌊 LAUT</div><button class="obj" style="left:45%;top:46%" onclick="App.inspect('ocean')">🌊</button>
    </div>
    <div class="section card"><h3>🔎 Penemuanmu</h3><div class="discoveries">${["Evaporasi","Transpirasi","Kondensasi","Presipitasi","Infiltrasi","Runoff"].map(x=>`<span class="tag ${this.state.discovered.includes(x)?"":"locked"}">${this.state.discovered.includes(x)?"✓":"🔒"} ${x}</span>`).join("")}</div><div class="next-row"><button class="btn btn-primary" onclick="App.go('explore')">Lanjut Eksplorasi →</button></div></div>`},
  inspect(key){const o=DATA.objects[key];if(!this.state.explored.includes(key))this.state.explored.push(key);let process={sun:"Evaporasi",ocean:"Evaporasi",cloud:"Kondensasi",plant:"Transpirasi",river:"Runoff",soil:"Infiltrasi",mountain:"Runoff",lake:"Evaporasi"}[key];if(process&&!this.state.discovered.includes(process))this.state.discovered.push(process);this.unlock("explore");Store.save();UI.modal(`<div class="eyebrow">Investigasi objek</div><h2>${o.icon} ${o.name}</h2><p>${o.info}</p><div class="notice"><b>Pertanyaan SAGE:</b><br>${o.q}</div><div class="next-row"><button class="btn btn-soft" onclick="UI.closeModal();SAGE.show('${o.q}')">Tanya SAGE 🌿</button><button class="btn btn-primary" onclick="UI.closeModal();App.go('explore')">Lanjut →</button></div>`);},
  explore(){return `<div class="eyebrow">02 · Observe</div><h2>🔎 Amati Sebelum Menebak</h2><p>Perhatikan fenomena sederhana ini.</p><div class="card" style="margin-top:16px;text-align:center"><div style="font-size:90px">💧 ☀️</div><h2>Genangan air terkena cahaya matahari</h2><p>Beberapa waktu kemudian, genangan terlihat semakin sedikit.</p><button class="btn btn-primary" onclick="App.go('predict')">Buat Prediksi →</button></div><div class="section cards"><div class="card"><h3>Yang kamu lihat</h3><p>Air di permukaan dapat berkurang ketika menerima panas.</p></div><div class="card"><h3>Yang belum kita tahu</h3><p>Ke mana air itu pergi? Inilah yang akan kita selidiki.</p></div></div>`},
  predict(){return `<div class="eyebrow">03 · Predict</div><h2>🔮 Buat Prediksimu</h2><p>Jangan mencari jawaban dulu. Nyatakan dugaanmu berdasarkan pengamatan.</p><div class="card" style="margin-top:15px"><h3>Ke mana perginya air dari genangan?</h3><div class="answer-grid">${["Air menghilang begitu saja","Air berubah menjadi uap","Air berubah menjadi tanah","Belum yakin"].map(a=>`<button class="answer ${this.state.prediction===a?"selected":""}" onclick="App.selectPrediction('${a}')">${a}</button>`).join("")}</div><label><b>Mengapa kamu memilih itu?</b></label><textarea class="input" id="predReason" placeholder="Tulis alasan singkat...">${this.state.predictionReason||""}</textarea><p><b>Seberapa yakin?</b></p><div class="confidence">${["Belum yakin","Cukup yakin","Sangat yakin"].map(c=>`<button class="${this.state.confidence===c?"active":""}" onclick="App.selectConfidence('${c}')">${c}</button>`).join("")}</div><button class="btn btn-primary" onclick="App.savePrediction()">Simpan Prediksi & Lanjut →</button></div>`},
  selectPrediction(a){this.state.prediction=a;Store.save();SAGE.show(SAGE.prediction(a,this.state.confidence)) ;this.render();},
  selectConfidence(c){this.state.confidence=c;Store.save();this.render();},
  savePrediction(){this.state.predictionReason=document.getElementById("predReason").value.trim();if(!this.state.prediction||!this.state.predictionReason){UI.toast("Pilih prediksi dan tulis alasanmu dulu.");return}this.unlock("predict");Store.save();this.go('lab')},
  lab(){return `<div class="eyebrow">04 · Experiment</div><h2>🔬 Laboratorium Penguapan</h2><p>Ubah kondisi eksperimen, lalu lihat bagaimana perubahan itu memengaruhi penguapan.</p><div class="lab-layout section"><div class="controls">
    ${[["heat","☀️ Intensitas panas",["Low","Medium","High"]],["amount","💧 Jumlah air",["Low","Medium","High"]],["air","🌬️ Pergerakan udara",["Low","Medium","High"]],["temp","🌡️ Suhu",["Cool","Normal","Warm"]]].map(c=>`<div class="control"><label>${c[1]}<span id="${c[0]}Val">${this.state.lab?.[c[0]]||c[2][1]}</span></label><select id="${c[0]}">${c[2].map(v=>`<option ${((this.state.lab?.[c[0]]||c[2][1])===v)?"selected":""}>${v}</option>`).join("")}</select></div>`).join("")}
    <button class="btn btn-primary" onclick="App.runExperiment()">▶ Jalankan Eksperimen</button>
    <button class="btn btn-soft" onclick="App.go('evidence')" ${this.state.experimentA?"":"disabled"}>Lihat Bukti →</button>
    </div><div class="experiment"><div class="beaker"><div class="steam" id="steam">💨 💨 💨</div><div class="droplets" id="droplets">💧 💧 💧</div><div class="beaker-glass"><div class="water" id="water"></div></div></div><h3>Model Penguapan</h3><p>Eksperimen menggunakan model sederhana agar kamu dapat membandingkan pengaruh variabel.</p><div id="results">${this.state.experimentA?this.resultHTML(this.state.experimentA):'<div class="empty">Jalankan eksperimen untuk melihat data.</div>'}</div></div></div>`},
  resultHTML(r){return `<div class="data-grid"><div class="metric"><small>Laju penguapan</small><strong>${r.rate}%</strong></div><div class="metric"><small>Uap air</small><strong>${r.vapor}</strong></div><div class="metric"><small>Waktu</small><strong>${r.time} mnt</strong></div></div><div class="bar" style="margin-top:15px"><i style="width:${r.rate}%"></i></div>`},
  runExperiment(){const s={heat:document.getElementById("heat").value,amount:document.getElementById("amount").value,air:document.getElementById("air").value,temp:document.getElementById("temp").value};this.state.lab=s;const r=Simulation.run(s);this.state.experimentA={...r,settings:s};this.unlock("experiment");Store.save();this.render();setTimeout(()=>{document.getElementById("steam")?.classList.add("show");document.getElementById("droplets")?.classList.add("show");const w=document.getElementById("water");if(w)w.style.height=r.remaining+"%";SAGE.show(SAGE.result(r));},250);},
  evidence(){const r=this.state.experimentA;return `<div class="eyebrow">05 · Analyze</div><h2>📊 Temukan Buktinya</h2><p>Gunakan hasil eksperimenmu, bukan tebakan.</p>${r?`<div class="card section"><h3>Data percobaanmu</h3><p>Panas: <b>${r.settings.heat}</b> · Air: <b>${r.settings.amount}</b> · Udara: <b>${r.settings.air}</b> · Suhu: <b>${r.settings.temp}</b></p>${this.resultHTML(r)}</div><div class="card section"><h3>Bukti yang paling penting</h3><p>Data mana yang paling membantu menjelaskan bahwa kondisi eksperimen memengaruhi penguapan?</p><div class="answer-grid">${[`Laju penguapan ${r.rate}%`,`Waktu ${r.time} menit`,`Semua data di atas`].map((x,i)=>`<button class="answer ${this.state.evidence&&i===2?"correct":""}" onclick="App.markEvidence(${i})">${x}</button>`).join("")}</div></div><div class="next-row"><button class="btn btn-primary" onclick="App.go('challenge')">Lanjut Tantangan →</button></div>`:'<div class="notice">Kamu perlu menjalankan eksperimen terlebih dahulu.</div><button class="btn btn-primary" onclick="App.go(\'lab\')">Ke Laboratorium</button>'}`},
  markEvidence(i){if(i===2){this.state.evidence=true;this.unlock("evidence");Store.save();SAGE.show("Bagus! Kamu menggunakan keseluruhan data sebagai bukti, lalu dapat mencari hubungan antarvariabel.");this.render()}else{SAGE.show("Coba lihat lagi. Bukti yang kuat sebaiknya mempertimbangkan hasil data secara keseluruhan.");}},
  challenge(){return `<div class="eyebrow">06 · Explain</div><h2>💧 Susun Siklus Air</h2><p>Hubungkan proses yang sudah kamu temukan. Pilih proses untuk mengisi bagian yang kosong.</p><div class="challenge-box section"><div class="cycle">${["Evaporasi","Kondensasi","Presipitasi","Infiltrasi"].map((x,i)=>`<div class="cycle-slot">${this.state.cycle?x:"? Pilih proses"}</div>${i<3?"→":""}`).join("")}</div><div class="processes">${["Evaporasi","Kondensasi","Presipitasi","Infiltrasi"].map(x=>`<button class="process" onclick="App.chooseCycle('${x}')">${x}</button>`).join("")}</div><p id="cycleMsg"></p></div><div class="card section"><h3>🧠 Jelaskan Temuanmu</h3><p>Gunakan hasil eksperimen untuk menjelaskan mengapa air dapat berubah menjadi uap.</p><textarea id="reason" class="input" placeholder="Contoh: panas membuat air...">${this.state.reasonText||""}</textarea><div class="next-row"><button class="btn btn-primary" onclick="App.saveReason()">Simpan Penjelasan →</button></div></div>`},
  chooseCycle(x){if(!this.state.cycle){if(!this.state.cycleSeq)this.state.cycleSeq=[];if(!this.state.cycleSeq.includes(x))this.state.cycleSeq.push(x);if(this.state.cycleSeq.length===4){this.state.cycle=true;this.unlock("cycle");Store.save();this.render();SAGE.show("Siklusmu lengkap! Perhatikan bahwa air terus bergerak dan berubah bentuk.");}else{Store.save();this.render();}}},
  saveReason(){const t=document.getElementById("reason").value.trim();if(t.length<10){UI.toast("Coba jelaskan sedikit lebih lengkap.");return}this.state.reasonText=t;this.state.reason=true;this.unlock("reason");Store.save();this.go('environment')},
  environment(){return `<div class="eyebrow">07 · Connect</div><h2>🌱 Bumi Membutuhkan Air</h2><p>Gunakan pemahamanmu untuk memikirkan masalah nyata.</p><div class="card section"><div style="font-size:70px">🏜️ ☀️ 🌱</div><h3>Daerah mengalami hujan yang sangat sedikit selama beberapa minggu.</h3><p>Prediksikan apa yang mungkin terjadi pada lingkungan.</p><div class="answer-grid">${["Tanaman dapat kekurangan air","Air tanah dan permukaan dapat berubah","Kondisi lingkungan dapat terpengaruh","Semua kemungkinan perlu dipertimbangkan"].map(x=>`<button class="answer" onclick="App.envAnswer(this,'${x}')">${x}</button>`).join("")}</div><div id="envReason" style="display:none"><textarea id="envText" class="input" placeholder="Jelaskan alasanmu..."></textarea><button class="btn btn-primary" style="margin-top:10px" onclick="App.saveEnv()">Simpan Aksi Lingkungan →</button></div></div>`},
  envAnswer(el,x){document.querySelectorAll(".answer").forEach(b=>b.classList.remove("selected"));el.classList.add("selected");document.getElementById("envReason").style.display="block";},
  saveEnv(){if(document.getElementById("envText").value.trim().length<10){UI.toast("Tambahkan alasanmu dulu.");return}this.state.environment=true;this.unlock("environment");Store.save();this.go('reflect')},
  reflect(){return `<div class="eyebrow">08 · Reflect</div><h2>🧠 Refleksi Ilmuwan</h2><p>Ilmuwan tidak berhenti setelah menemukan hasil. Mereka memikirkan apa yang dipelajari.</p><div class="reflection section"><div class="card"><h3>1. Apa hal baru yang kamu temukan?</h3><textarea id="r1" class="input">${this.state.reflection.r1||""}</textarea></div><div class="card"><h3>2. Apakah hasil eksperimen sesuai prediksi?</h3><textarea id="r2" class="input">${this.state.reflection.r2||""}</textarea></div><div class="card"><h3>3. Apa yang akan kamu ubah jika mengulang eksperimen?</h3><textarea id="r3" class="input">${this.state.reflection.r3||""}</textarea></div></div><button class="btn btn-primary" onclick="App.saveReflection()">Selesaikan Perjalanan 🏆</button>`},
  saveReflection(){const r={r1:document.getElementById("r1").value.trim(),r2:document.getElementById("r2").value.trim(),r3:document.getElementById("r3").value.trim()};if(Object.values(r).some(x=>x.length<5)){UI.toast("Lengkapi ketiga refleksi terlebih dahulu.");return}this.state.reflection=r;this.unlock("sage");Store.save();this.go('profile')},
  profile(){const s=this.state;return `<div class="hero"><div class="eyebrow">Your Scientist Profile</div><h1>🏆 Profil Ilmuwan</h1><p>Progress ini terbentuk dari tindakan yang benar-benar kamu lakukan selama investigasi.</p><div class="progress"><i style="width:${this.progress()}%"></i></div><h3>${this.progress()}% perjalanan selesai</h3></div><section class="section"><div class="section-title"><h2>Pencapaian</h2><p>${s.achievements.length}/${DATA.achievements.length} terbuka</p></div><div class="profile-grid">${DATA.achievements.map(a=>`<div class="achievement ${s.achievements.includes(a[0])?"":"locked"}"><div class="medal">${a[1]}</div><h3>${a[2]}</h3><small>${s.achievements.includes(a[0])?"✓ Unlocked":"🔒 Locked"} · ${a[3]}</small></div>`).join("")}</div></section><section class="section cards"><div class="card"><h3>Observasi</h3><p>${s.explored.length} objek dieksplorasi.</p></div><div class="card"><h3>Eksperimen</h3><p>${s.experimentA?"1 percobaan selesai":"Belum ada percobaan."}</p></div><div class="card"><h3>Penalaran</h3><p>${s.reason?"Selesai":"Belum selesai"}</p></div></section><div class="next-row"><button class="btn btn-primary" onclick="App.go('home')">Kembali ke Beranda</button><button class="btn btn-soft" onclick="App.reset()">Mulai dari Awal</button></div>`}
};
document.addEventListener("DOMContentLoaded",()=>App.init());