const Store={
  key:"sageAI_v2",
  default:{page:"home",discovered:[],explored:[],prediction:null,confidence:null,predictionReason:"",experimentA:null,experimentB:null,evidence:false,reason:false,cycle:false,cycleSeq:[],environment:false,envChoice:"",reflection:{},achievements:[]},
  load(){try{return {...this.default,...JSON.parse(localStorage.getItem(this.key)||"{}")}}catch{return {...this.default}}},
  save(){localStorage.setItem(this.key,JSON.stringify(App.state))}
};
const UI={
  modal(html){document.getElementById("modalContent").innerHTML=html;document.getElementById("modal").classList.remove("hidden")},
  closeModal(){document.getElementById("modal").classList.add("hidden")},
  toast(t){const x=document.createElement("div");x.className="toast";x.textContent=t;document.body.appendChild(x);setTimeout(()=>x.remove(),1800)}
};
const App={
  state:Store.load(),
  pages:["home","world","explore","predict","lab","evidence","challenge","environment","reflect","profile"],
  init(){this.render()},
  go(page){this.state.page=page;Store.save();this.render()},
  reset(){if(confirm("Mulai kembali dari awal? Progress akan dihapus.")){localStorage.removeItem(Store.key);this.state=Store.load();this.render()}},
  progress(){const s=this.state;const checks=[s.explored.length>=7,s.prediction&&s.predictionReason,!!s.experimentA,!!s.evidence,!!s.cycle,s.reason,!!s.environment,Object.keys(s.reflection).length>=3];return Math.round(checks.filter(Boolean).length/checks.length*100)},
  unlock(id){if(!this.state.achievements.includes(id)){this.state.achievements.push(id);Store.save();UI.toast("Pencapaian baru terbuka!")}},
  render(){const p=this.state.page||"home";const views={home:this.home,world:this.world,explore:this.explore,predict:this.predict,lab:this.lab,evidence:this.evidence,challenge:this.challenge,environment:this.environment,reflect:this.reflect,profile:this.profile};document.getElementById("screen").innerHTML=views[p].call(this);this.afterRender()},
  afterRender(){const pr=this.progress();document.getElementById("progressBar").style.width=pr+"%";document.getElementById("progressLabel").textContent=pr+"% perjalanan";document.querySelectorAll("[data-nav]").forEach(b=>b.classList.toggle("active",b.dataset.nav===this.state.page));let sage=document.getElementById("sageBox");if(!sage){document.body.insertAdjacentHTML("beforeend",`<div id="sageBox" class="sage"><div class="sage-head"><div class="sage-avatar">🌿</div><div><strong>SAGE</strong><small>Pendamping Investigasi</small></div><button class="sage-close" onclick="SAGE.close()">×</button></div><p id="sageText"></p></div>`)}},
  home(){const p=this.progress();return `<div class="page home-page"><section class="home-main"><div class="eyebrow">SMART ADAPTIVE GUIDE</div><h1>SAGE-AI 🌿</h1><h2>Laboratorium Sains Digital</h2><p class="lead"><b>Selidiki ke mana perginya air.</b><br>Amati → Prediksi → Eksperimen → Buktikan.</p><button class="btn btn-primary big-btn" onclick="App.go('world')">Mulai Investigasi →</button></section><section class="home-side"><div class="mission"><span class="big">💧</span><div><b>Misi Ilmuwan</b><p>Gunakan bukti untuk menjelaskan perjalanan air.</p></div></div><div class="step-strip">${[["01","Explore"],["02","Observe"],["03","Predict"],["04","Experiment"],["05","Analyze"],["06","Explain"],["07","Connect"],["08","Reflect"]].map(x=>`<div><b>${x[0]}</b><span>${x[1]}</span></div>`).join("")}</div><div class="home-progress"><div><b>Perjalananmu</b><strong>${p}%</strong></div><div class="bar"><i style="width:${p}%"></i></div><small>Setiap tahap tersimpan otomatis.</small></div></section></div>`},
  world(){return `<div class="page world-page"><div class="page-head"><div><div class="eyebrow">01 · EXPLORE</div><h2>Dunia Air</h2><p>Sentuh objek. Gerakkan. Temukan petunjuk.</p></div><div class="counter">${this.state.explored.length}/7</div></div><div class="world"><button class="obj sun" onclick="App.inspect('sun')">☀️<span>Matahari</span></button><button class="obj cloud" onclick="App.inspect('cloud')">☁️<span>Awan</span></button><button class="obj cloud2" onclick="App.inspect('cloud')">☁️</button><button class="obj mountain" onclick="App.inspect('mountain')">🏔️<span>Pegunungan</span></button><button class="obj tree" onclick="App.inspect('plant')">🌳<span>Tumbuhan</span></button><button class="obj tree2" onclick="App.inspect('plant')">🌲</button><button class="obj lake" onclick="App.inspect('lake')">💧<span>Danau</span></button><button class="obj river" onclick="App.inspect('river')">🏞️<span>Sungai</span></button><button class="obj soil" onclick="App.inspect('soil')">🌱<span>Tanah</span></button><button class="obj rain" onclick="App.inspect('cloud')">🌧️<span>Hujan</span></button><button class="obj ocean" onclick="App.inspect('ocean')">🌊<span>Laut</span></button></div><div class="world-footer"><div class="discoveries">${["Evaporasi","Transpirasi","Kondensasi","Presipitasi","Infiltrasi","Runoff"].map(x=>`<span class="tag ${this.state.discovered.includes(x)?"found":"locked"}">${this.state.discovered.includes(x)?"✓":"○"} ${x}</span>`).join("")}</div><button class="btn btn-primary" onclick="App.go('explore')" ${this.state.explored.length<1?"disabled":""}>Lanjut ke Pengamatan →</button></div></div>`},
  inspect(key){const o=DATA.objects[key];if(!this.state.explored.includes(key))this.state.explored.push(key);const process={sun:"Evaporasi",ocean:"Evaporasi",cloud:"Kondensasi",plant:"Transpirasi",river:"Runoff",soil:"Infiltrasi",mountain:"Runoff",lake:"Evaporasi"}[key];if(process&&!this.state.discovered.includes(process))this.state.discovered.push(process);this.unlock("explore");Store.save();const extra=key==='sun'?`<div class="mini-interact"><b>Coba atur panas</b><input type="range" min="1" max="3" value="2" oninput="App.quickHeat(this.value)"><div id="quickHeat">Sedang · air mulai menerima panas.</div></div>`:`<div class="notice"><b>Pertanyaan SAGE</b><br>${o.q}</div>`;UI.modal(`<div class="eyebrow">PETUNJUK DITEMUKAN</div><div class="modal-icon">${o.icon}</div><h2>${o.name}</h2><p>${o.info}</p>${extra}<div class="next-row"><button class="btn btn-soft" onclick="UI.closeModal();SAGE.show('${o.q.replace(/'/g,"\\'")}')">Tanya SAGE</button><button class="btn btn-primary" onclick="UI.closeModal()">Lanjut ✓</button></div>`);},
  quickHeat(v){const t=["Rendah · perubahan lebih lambat.","Sedang · air mulai menerima panas.","Tinggi · penguapan dapat berlangsung lebih cepat."][Number(v)-1];document.getElementById("quickHeat").textContent=t;document.getElementById("sageText")&&(document.getElementById("sageText").textContent=t)},
  explore(){return `<div class="page activity-page"><div class="page-head"><div><div class="eyebrow">02 · OBSERVE</div><h2>Amati Sebelum Menebak</h2><p>Geser waktu dan lihat perubahan genangan.</p></div><span class="status-dot">● Observasi</span></div><div class="observe-card"><div class="observe-scene"><div class="obs-sun">☀️</div><div class="obs-ground"></div><div class="puddle" id="puddle"><span>💧</span></div><div class="obs-vapor" id="obsVapor">· · ·</div></div><div class="time-row"><b>Waktu</b><input id="obsTime" type="range" min="0" max="3" value="0" oninput="App.observeTime(this.value)"><span id="obsLabel">Awal</span></div><div class="observe-note" id="obsNote">Genangan masih terlihat jelas.</div></div><div class="action-row"><button class="btn btn-soft" onclick="SAGE.show('Perhatikan ukuran genangan. Apa yang berubah ketika waktu berlalu?')">Petunjuk SAGE</button><button class="btn btn-primary" onclick="App.markObserve();App.go('predict')">Sudah Mengamati →</button></div></div>`},
  observeTime(v){const sizes=[72,58,42,25];const labels=["Awal","Beberapa menit","Lebih lama","Setelah cukup lama"];const notes=["Genangan masih terlihat jelas.","Permukaan air mulai berkurang.","Genangan tampak semakin kecil.","Sebagian air tidak lagi terlihat di permukaan."];const p=document.getElementById('puddle');if(p)p.style.width=sizes[v]+"%";document.getElementById('obsLabel').textContent=labels[v];document.getElementById('obsNote').textContent=notes[v];document.getElementById('obsVapor').style.opacity=v>0?1:0},
  markObserve(){this.state.explored=[...new Set([...this.state.explored,"observation"])] ;Store.save()},
  predict(){const answers=["Air menghilang begitu saja","Air berubah menjadi uap","Air berubah menjadi tanah","Belum yakin"];return `<div class="page activity-page"><div class="page-head"><div><div class="eyebrow">03 · PREDICT</div><h2>Buat Prediksimu</h2><p>Nyatakan dugaan sebelum melihat hasil eksperimen.</p></div><span class="status-dot">● Dugaan</span></div><div class="predict-layout"><div class="question-card"><div class="question-no">PERTANYAAN</div><h3>Ke mana perginya air dari genangan?</h3><div class="answer-grid">${answers.map(a=>`<button class="answer ${this.state.prediction===a?"selected":""}" onclick="App.selectPrediction('${a}')">${a}</button>`).join("")}</div></div><div class="reason-card"><label><b>Alasanmu</b><small>1–2 kalimat cukup.</small></label><textarea class="input compact" id="predReason" placeholder="Karena..."></textarea><div class="confidence"><b>Keyakinan:</b>${["Belum yakin","Cukup yakin","Sangat yakin"].map(c=>`<button class="${this.state.confidence===c?"active":""}" onclick="App.selectConfidence('${c}')">${c}</button>`).join("")}</div></div></div><div class="action-row"><button class="btn btn-soft" onclick="SAGE.show('Prediksi boleh salah. Yang penting kamu punya alasan untuk mengujinya.')">Butuh petunjuk?</button><button class="btn btn-primary" onclick="App.savePrediction()">Simpan & Eksperimen →</button></div></div>`},
  selectPrediction(a){this.state.prediction=a;Store.save();SAGE.show(SAGE.prediction(a,this.state.confidence));this.render()},
  selectConfidence(c){this.state.confidence=c;Store.save();this.render()},
  savePrediction(){this.state.predictionReason=document.getElementById("predReason").value.trim();if(!this.state.prediction||!this.state.predictionReason){UI.toast("Pilih prediksi dan tulis alasannya dulu.");return}this.unlock("predict");Store.save();this.go('lab')},
  lab(){const vals=[['heat','☀️ Panas',['Low','Medium','High']],['amount','💧 Jumlah air',['Low','Medium','High']],['air','💨 Angin',['Low','Medium','High']],['temp','🌡️ Suhu',['Cool','Normal','Warm']]];return `<div class="page lab-page"><div class="page-head"><div><div class="eyebrow">04 · EXPERIMENT</div><h2>Laboratorium Penguapan</h2><p>Ubah kondisi, jalankan simulasi, lalu baca datanya.</p></div><span class="status-dot">● Eksperimen</span></div><div class="lab-grid"><div class="control-panel">${vals.map(c=>`<div class="control"><label>${c[1]}<span>${this.state.lab?.[c[0]]||c[2][1]}</span></label><select id="${c[0]}">${c[2].map(v=>`<option ${((this.state.lab?.[c[0]]||c[2][1])===v)?'selected':''}>${v}</option>`).join('')}</select></div>`).join('')}<button class="btn btn-primary" onclick="App.runExperiment()">▶ Jalankan Simulasi</button></div><div class="experiment"><div class="beaker"><div class="steam" id="steam">💨 💨</div><div class="beaker-glass"><div class="water" id="water"></div></div></div><div class="experiment-state" id="expState">${this.state.experimentA?"Hasil terakhir tersimpan.":"Siap diuji."}</div><div id="results">${this.state.experimentA?this.resultHTML(this.state.experimentA):'<div class="empty">Atur variabel lalu jalankan.</div>'}</div></div></div><div class="action-row"><button class="btn btn-soft" onclick="SAGE.show('Coba ubah satu variabel saja. Dengan begitu kamu lebih mudah melihat pengaruhnya.')">Tips eksperimen</button><button class="btn btn-primary" onclick="App.go('evidence')" ${this.state.experimentA?'':'disabled'}>Analisis Data →</button></div></div>`},
  resultHTML(r){return `<div class="data-grid"><div class="metric"><small>Laju penguapan</small><strong>${r.rate}%</strong></div><div class="metric"><small>Uap air</small><strong>${r.vapor}</strong></div><div class="metric"><small>Waktu</small><strong>${r.time} mnt</strong></div></div><div class="bar"><i style="width:${r.rate}%"></i></div>`},
  runExperiment(){const s={heat:document.getElementById("heat").value,amount:document.getElementById("amount").value,air:document.getElementById("air").value,temp:document.getElementById("temp").value};this.state.lab=s;const r=Simulation.run(s);this.state.experimentA={...r,settings:s};this.unlock("experiment");Store.save();this.render();setTimeout(()=>{document.getElementById("steam")?.classList.add("show");const w=document.getElementById("water");if(w)w.style.height=r.remaining+"%";SAGE.show(SAGE.result(r));},180)},
  evidence(){const r=this.state.experimentA;if(!r)return `<div class="page activity-page"><div class="eyebrow">05 · ANALYZE</div><h2>Temukan Buktinya</h2><div class="notice">Jalankan eksperimen terlebih dahulu.</div><button class="btn btn-primary" onclick="App.go('lab')">Ke Laboratorium →</button></div>`;return `<div class="page activity-page"><div class="page-head"><div><div class="eyebrow">05 · ANALYZE</div><h2>Temukan Buktinya</h2><p>Gunakan hasil eksperimenmu, bukan tebakan.</p></div><span class="status-dot">● Data</span></div><div class="data-review"><div class="card"><h3>Hasil percobaan</h3><p>${r.settings.heat} panas · ${r.settings.amount} air · ${r.settings.air} angin · ${r.settings.temp} suhu</p>${this.resultHTML(r)}</div><div class="card"><h3>Data mana yang paling membantu?</h3><div class="answer-grid">${[`Laju penguapan ${r.rate}%`,`Waktu ${r.time} menit`,`Semua data di atas`].map((x,i)=>`<button class="answer ${this.state.evidence&&i===2?'correct':''}" onclick="App.markEvidence(${i})">${x}</button>`).join('')}</div><div class="notice small-notice">Petunjuk: kesimpulan yang kuat tidak hanya bergantung pada satu angka.</div></div></div><div class="action-row"><button class="btn btn-soft" onclick="SAGE.show('Bandingkan laju, uap air, dan waktu. Apa hubungan ketiganya?')">Bantuan SAGE</button><button class="btn btn-primary" onclick="App.go('challenge')" ${this.state.evidence?'':'disabled'}>Lanjut Explain →</button></div></div>`},
  markEvidence(i){if(i===2){this.state.evidence=true;this.unlock("evidence");Store.save();this.render();SAGE.show("Bagus. Kamu mempertimbangkan seluruh data sebelum membuat kesimpulan.")}else SAGE.show("Coba pertimbangkan seluruh hasil data, bukan hanya satu angka.")},
  challenge(){const seq=this.state.cycleSeq||[];const steps=["Evaporasi","Kondensasi","Presipitasi","Infiltrasi"];return `<div class="page activity-page"><div class="page-head"><div><div class="eyebrow">06 · EXPLAIN</div><h2>Susun Siklus Air</h2><p>Pilih proses sesuai urutan yang kamu pahami.</p></div><span class="counter">${seq.length}/4</span></div><div class="cycle-board"><div class="cycle-slots">${steps.map((_,i)=>`<div class="cycle-slot">${seq[i]||"?"}</div>${i<3?'<span>→</span>':''}`).join('')}</div><div class="processes">${steps.map(x=>`<button class="process ${seq.includes(x)?'used':''}" onclick="App.chooseCycle('${x}')">${x}</button>`).join('')}</div><p class="cycle-help">${seq.length<4?'Pilih proses satu per satu.':''}</p></div><div class="reason-card"><label><b>Jelaskan temuanmu</b><small>Gunakan hasil eksperimen.</small></label><textarea id="reason" class="input compact" placeholder="Panas membuat air...">${this.state.reasonText||''}</textarea></div><div class="action-row"><button class="btn btn-soft" onclick="SAGE.show('Hubungkan perubahan air dengan panas dan data percobaanmu.')">Petunjuk SAGE</button><button class="btn btn-primary" onclick="App.saveReason()" ${seq.length===4?'':'disabled'}>Simpan Penjelasan →</button></div></div>`},
  chooseCycle(x){const seq=this.state.cycleSeq||[];if(seq.includes(x)){UI.toast("Proses itu sudah dipilih.");return}seq.push(x);this.state.cycleSeq=seq;if(seq.length===4){this.state.cycle=seq.join('|')===`Evaporasi|Kondensasi|Presipitasi|Infiltrasi`;if(this.state.cycle)this.unlock('cycle');}Store.save();this.render();if(seq.length===4&&!this.state.cycle)SAGE.show('Urutannya belum tepat. Coba pikirkan apa yang terjadi setelah air menguap.');},
  saveReason(){const t=document.getElementById('reason').value.trim();if(t.length<10){UI.toast('Jelaskan sedikit lebih lengkap.');return}if(!this.state.cycle){UI.toast('Susun siklus dengan urutan yang tepat dulu.');return}this.state.reasonText=t;this.state.reason=true;this.unlock('reason');Store.save();this.go('environment')},
  environment(){const options=["Tanaman dapat kekurangan air","Air tanah dan permukaan dapat berubah","Kondisi lingkungan dapat terpengaruh","Semua kemungkinan perlu dipertimbangkan"];return `<div class="page activity-page"><div class="page-head"><div><div class="eyebrow">07 · CONNECT</div><h2>Sains di Lingkungan</h2><p>Gunakan pemahamanmu pada situasi nyata.</p></div><span class="status-dot">● Aksi</span></div><div class="environment-card"><div class="env-scene">🏜️ ☀️ 🌱</div><h3>Hujan sangat sedikit selama beberapa minggu.</h3><p>Apa yang mungkin terjadi pada lingkungan?</p><div class="answer-grid">${options.map(x=>`<button class="answer ${this.state.envChoice===x?'selected':''}" onclick="App.envAnswer(this,'${x}')">${x}</button>`).join('')}</div><div id="envReason" class="env-reason" style="${this.state.envChoice?'':'display:none'}"><textarea id="envText" class="input compact" placeholder="Karena..."></textarea></div></div><div class="action-row"><button class="btn btn-soft" onclick="SAGE.show('Pikirkan hubungan hujan, tanah, tumbuhan, dan ketersediaan air.')">Petunjuk SAGE</button><button class="btn btn-primary" onclick="App.saveEnv()" ${this.state.envChoice?'':'disabled'}>Lanjut Refleksi →</button></div></div>`},
  envAnswer(el,x){this.state.envChoice=x;document.querySelectorAll('.environment-card .answer').forEach(b=>b.classList.remove('selected'));el.classList.add('selected');document.getElementById('envReason').style.display='block';Store.save()},
  saveEnv(){const t=document.getElementById('envText')?.value.trim()||'';if(t.length<10){UI.toast('Tambahkan alasan singkat.');return}this.state.environment=true;this.state.envReason=t;this.unlock('environment');Store.save();this.go('reflect')},
  reflect(){const r=this.state.reflection||{};return `<div class="page activity-page"><div class="page-head"><div><div class="eyebrow">08 · REFLECT</div><h2>Refleksi Ilmuwan</h2><p>Pikirkan kembali proses penyelidikanmu.</p></div><span class="counter">3 pertanyaan</span></div><div class="reflection-grid">${[["r1","Apa hal baru yang kamu temukan?"],["r2","Apakah hasil eksperimen sesuai prediksi?"],["r3","Apa yang akan kamu ubah jika mengulang?"]].map((x,i)=>`<div class="card reflection-card"><span>${i+1}</span><label>${x[1]}</label><textarea id="${x[0]}" class="input compact">${r[x[0]]||''}</textarea></div>`).join('')}</div><div class="action-row"><button class="btn btn-soft" onclick="SAGE.show('Refleksi membantu ilmuwan belajar dari proses, bukan hanya hasil.')">Petunjuk SAGE</button><button class="btn btn-primary" onclick="App.saveReflection()">Selesaikan Perjalanan 🏆</button></div></div>`},
  saveReflection(){const r={r1:document.getElementById('r1').value.trim(),r2:document.getElementById('r2').value.trim(),r3:document.getElementById('r3').value.trim()};if(Object.values(r).some(x=>x.length<5)){UI.toast('Lengkapi ketiga refleksi.');return}this.state.reflection=r;this.unlock('sage');Store.save();this.go('profile')},
  profile(){const s=this.state;const pct=this.progress();return `<div class="page profile-page"><section class="profile-head"><div><div class="eyebrow">SCIENTIST PROFILE</div><h1>Profil Ilmuwan</h1><p>Jejak belajarmu berdasarkan aktivitas yang sudah dilakukan.</p></div><div class="profile-pct"><strong>${pct}%</strong><span>selesai</span></div></section><div class="profile-stats"><div><b>${s.explored.filter(x=>x!=='observation').length}</b><small>Objek</small></div><div><b>${s.experimentA?1:0}</b><small>Eksperimen</small></div><div><b>${s.discovered.length}</b><small>Temuan</small></div><div><b>${s.achievements.length}/8</b><small>Badge</small></div></div><section class="achievement-strip">${DATA.achievements.map(a=>`<div class="achievement ${s.achievements.includes(a[0])?'':'locked'}"><div>${a[1]}</div><b>${a[2]}</b><small>${s.achievements.includes(a[0])?'Terbuka':'Terkunci'}</small></div>`).join('')}</section><div class="completion-card">${pct===100?'🎉 Perjalanan investigasi selesai!':'🔎 Masih ada tahap yang belum selesai.'}<button class="btn btn-primary" onclick="App.go('home')">Kembali ke Beranda</button></div></div>`}
};
document.addEventListener("DOMContentLoaded",()=>App.init());
